#
#    __   __   _         ___         _
#    \ \ / /__| |_ ___  / __|_  _ __| |_ ___ _ __
#     \ V / _ \  _/ -_) \__ \ || (_-<  _/ -_) '  \
#      \_/\___/\__\___| |___/\_, /__/\__\___|_|_|_|
#                            |__/
#

#  Vote System
#  Version: 1.0
#  Created by: Miquiis
#  Discord: Miquiis 5920

# Time related to the cooldown between votes, in seconds.
vote-cooldown: 60

# Time related to the amount of seconds a poll vote can stay up.
# After x seconds, the poll will close automatically since it took x amount of seconds without being completed
# Just to be 100% clear, because I can't explain this better.
# It's in seconds okay, don't forget about that.
# I'll stop, sorry.
vote-timeout: 300

# List of all votes, you can name it whatever you would like, just keep it without spaces!
votes:
  day:
    # Added new customize-able message per vote.
    vote-start-message: "&bVote to day time has started!\n&aType &eYES\n&cType &eNO&c to deny."
    # Added new customize-able message per vote.
    vote-success-message: "&bThe sun is now up!"
    # Added new customize-able message per vote.
    vote-fail-message: "&cThe vote to start the day has failed."
    commands:
      - "time set 0"
      - "say It's day now! :D"
  night:
    # Added new customize-able message per vote.
    vote-start-message: "&bVote to night time has started!\n&aType &eYES\n&cType &eNO&c to deny."
    # Added new customize-able message per vote.
    vote-success-message: "&bThe night has fallen."
    # Added new customize-able message per vote.
    vote-fail-message: "&cThe vote to start the night has failed."
    # Added to need exactly 5 votes to be successful. If you don't want any restrictions, just don't add the vote-restriction tab. Like vote day above.
    vote-restriction: 5
    commands:
      - "time set 16000"
      - "say It's night now! :D"
  kick:
    # Added new customize-able message per vote.
    vote-start-message: "&bVote to kick %player% has started!\n&aType &eYES\n&cType &eNO&c to deny."
    # Added new customize-able message per vote.
    vote-success-message: "&bThe player %PLAYER% was kicked."
    # Added new customize-able message per vote.
    vote-fail-message: "&cThe vote to kick %PLAYER% failed."
    # Added new vote types, to vote to an specific player, just use vote-type as player!
    vote-type: player
    # Added a new way to immune players. Only compatible with Teams.
    vote-immune: Speedrunner
    # Added a new way to stop the vote whenever the game starts. Only compatible with LobbyRestart.
    vote-ignore-in: lobby-locked
    # Added new vote percentage system for votes. It can be combined with vote-restriction.
    vote-percentage: 60
    commands:
      - "say The player %PLAYER% was voted out!"
      - "kick %PLAYER% &cYou were vote out by other players."